### ISSUE TITLE
Cannot get access to checkbox

### ISSUE THREAD

**Issue by wadehenning** [gushonorato/mechanizex#34]
I have never tried web scraping before and your package is helpful.  In my case, I can not access the html of the page until I click a checkbox (see the message below:  _"You must agree to the prohibitions..."_) but I can't click the checkbox without the page html, right?  I do know the id of the input: `id="agree_statement"`.  It is possible to check this input directly without first importing the page html? 
![image](https://user-images.githubusercontent.com/10761087/126045306-9a448a11-1dce-444a-82ab-5047c09cdd6d.png)

**Comment by wadehenning** [comment]
My bad.  There was a redirect I was not handling.  The proper path should have ended with /search/home/

This returns a page of javascript.  If you would like, I could open a new issue with this question, but is there a way to crawl a javascript page using this functionality?  (I do consider the original question closed)

**Comment by gushonorato** [comment]
Hey! 

Mecanize automatically handles 3xx redirects. 

Regarding your JavaScript question, one of the goals of Mechanize is to be simple and lightweight. To scrape JavaScript websites you'll have to use a full web browser automation package like Hound, which is very resource-consuming and hard to scale. However, in most cases, there's a workaround. Since all SPA has an API behind it, you can mimic all front-end web requests and consume its data without using a full browser.

**Comment by wadehenning** [comment]
@gushonorato  That's a great answer, thank you.
